site_name: JershLabs
site_url: https://jershbytes.github.io/jershlabs-docs
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: slate
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to Alliance mode
      primary: red
      accent: purple
    - scheme: default
      toggle:
        icon: material/toggle-switch
        name: Switch to Horde mode
      primary: blue
      accent: lime

plugins:
  - social
  - search

markdown_extensions:
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

copyright: |
  &copy; 2025 <a href="https://github.com/jershbytes"  target="_blank" rel="noopener">JershBytes</a>
